/**
 * Writes the installed EUI theme's tokens as CSS custom properties, for the static HTML design
 * boards in design/boards/. The boards then use the same colours, sizes, fonts and radii as
 * the app, in light and dark.
 *
 *   npm run tokens                      -> ../design/tokens.css
 *   node scripts/export-tokens.mjs <out>
 *
 * Light values sit on :root, dark values on [data-theme="dark"]. Names follow the theme's
 * own keys: --color-textParagraph, --size-m, --radius-control, --font-family.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { getComputed } = require('@elastic/eui');
const { EuiThemeBorealis } = require('@elastic/eui-theme-borealis');

const out = resolve(process.argv[2] ?? '../design/tokens.css');

function vars(mode) {
  const t = getComputed(EuiThemeBorealis, {}, mode);
  const lines = [];
  for (const [key, value] of Object.entries(t.colors)) {
    if (typeof value === 'string') lines.push(`--color-${key}: ${value};`);
  }
  for (const [key, value] of Object.entries(t.colors.vis ?? {})) {
    if (typeof value === 'string') lines.push(`--vis-${key}: ${value};`);
  }
  for (const [key, value] of Object.entries(t.colors.severity ?? {})) {
    if (typeof value === 'string') lines.push(`--severity-${key}: ${value};`);
  }
  return { t, lines };
}

const light = vars('LIGHT');
const dark = vars('DARK');
const t = light.t;
const shared = [
  `--font-family: ${t.font.family};`,
  `--font-family-code: ${t.font.familyCode};`,
  ...Object.entries(t.font.scale).map(([k, v]) => `--font-${k}: ${v}rem;`),
  ...Object.entries(t.font.weight).map(([k, v]) => `--weight-${k}: ${v};`),
  ...Object.entries(t.size).map(([k, v]) => `--size-${k}: ${v};`),
  ...Object.entries(t.border.radius).map(([k, v]) => `--radius-${k}: ${v};`),
  `--border-width-thin: ${t.border.width.thin};`,
  `--border-width-thick: ${t.border.width.thick};`,
];

const css = `/*
 * Generated by ui/scripts/export-tokens.mjs from the installed theme (${t.themeName}).
 * Do not edit by hand; run \`npm run tokens\` in ui/ after a theme upgrade.
 * Light on :root, dark on [data-theme="dark"]. Body text size is --font-s (${t.font.scale.s}rem).
 */
:root {
  ${shared.join('\n  ')}
  ${light.lines.join('\n  ')}
}

[data-theme='dark'] {
  ${dark.lines.join('\n  ')}
}
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css);
console.log(`wrote ${out} (${light.lines.length} colour tokens per mode)`);
