/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as DevMockRouteImport } from './routes/dev/mock'
import { Route as DevSmokeRouteImport } from './routes/dev/smoke'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMockRoute = DevMockRouteImport.update({
  id: '/dev/mock',
  path: '/dev/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSmokeRoute = DevSmokeRouteImport.update({
  id: '/dev/smoke',
  path: '/dev/smoke',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/mock': typeof DevMockRoute
  '/dev/smoke': typeof DevSmokeRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/mock': typeof DevMockRoute
  '/dev/smoke': typeof DevSmokeRoute
  '/dev': typeof DevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/mock': typeof DevMockRoute
  '/dev/smoke': typeof DevSmokeRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/components' | '/dev/mock' | '/dev/smoke' | '/dev/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/components' | '/dev/mock' | '/dev/smoke' | '/dev'
  id:
    '__root__' | '/' | '/dev/components' | '/dev/mock' | '/dev/smoke' | '/dev/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevComponentsRoute: typeof DevComponentsRoute
  DevMockRoute: typeof DevMockRoute
  DevSmokeRoute: typeof DevSmokeRoute
  DevIndexRoute: typeof DevIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/mock': {
      id: '/dev/mock'
      path: '/dev/mock'
      fullPath: '/dev/mock'
      preLoaderRoute: typeof DevMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/smoke': {
      id: '/dev/smoke'
      path: '/dev/smoke'
      fullPath: '/dev/smoke'
      preLoaderRoute: typeof DevSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevComponentsRoute: DevComponentsRoute,
  DevMockRoute: DevMockRoute,
  DevSmokeRoute: DevSmokeRoute,
  DevIndexRoute: DevIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
